### ISSUE TITLE
Does not parse Debug directory as array of debug entries

### ISSUE THREAD

**Issue by Lima-X** [hasherezade/pe-bear#15]
pe bear seems to interpret the debug directory as a single entry, when in reality its a array who's size is determined by the size in the optional header debug data directory\
this is part of the spec as mentioned here https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#debug-directory-image-only\
\> Image files contain an optional debug directory that indicates what form of debug information is present and where it is. This directory consists of an array of debug directory entries whose location and size are indicated in the image optional header.

![image](https://user-images.githubusercontent.com/35961248/208322816-bdec7d68-842f-4fef-9c44-2f90905d989b.png)
the blue bytes represent the codeview directory which is usually the first and is parsed, the binary from the example has 2 additional entries it misses here marked red.

this is rather not critical but just a small oversight, would be nice as an enhancement tho

**Comment by hasherezade** [comment]
hi @Lima-X ! thanks for the heads-up! it will be fixed soon

**Comment by hasherezade** [comment]
@Lima-X - I fixed it, this is a demo of how it looks now:

![debug_records](https://user-images.githubusercontent.com/3115348/220401745-e39ffbac-7311-45f0-af34-2a5c02e436f1.png)

Would you like to test the new version pre-release? You can download the builds from AppVeyor server, as described in the [README](https://github.com/hasherezade/pe-bear#builds).

**Comment by hasherezade** [comment]
available in the latest release: 
+ https://github.com/hasherezade/pe-bear/releases/tag/v0.6.5
