### ISSUE TITLE
PE Bear can not add a new library to import table of a 64 bit dll

### ISSUE THREAD

**Issue by hmirheydari** [hasherezade/pe-bear#16]
I have tried to add a new library to import table of a 64 bit dll, but it adds only two red rows that can not be edited as the screenshot that can be viewed at: https://terabox.com/s/1AceZNzi9rpUFOpCEP4Dq9g
![pe bear bug](https://user-images.githubusercontent.com/3115348/214126243-0ca193a3-e8f8-42d1-88cb-098288b446af.jpg)

**Comment by hasherezade** [comment]
hi @hmirheydari !
It seems like a situation that was described here: https://github.com/hasherezade/pe-bear-releases/wiki/Import-adding
The rows are red and cannot be edited, because you are supposed to begin by setting a valid addresses in "NameRVA", "FirstThunk" and "OriginalFirstThunk". Once you fill those RVAs with proper values, you will be able to edit the name, etc.

**Comment by hmirheydari** [comment]
Hi @hasherezade 
Thanks, please view the video that can be downloaded from https://terabox.com/s/14642Y4l4s7dS2X5QRJu-MA
I can not change any property of added library, your help is appreciated.

**Comment by hasherezade** [comment]
@hmirheydari - thanks for the video, now I see what is the problem. I think this will help:

![](https://raw.githubusercontent.com/wiki/hasherezade/pe-bear/img/add_import/step5-a.png)

I added a note about it to the Wiki, Step 5: https://github.com/hasherezade/pe-bear/wiki/Import-adding#step-5

Please let me know if it works for you.

**Comment by hmirheydari** [comment]
Hi Hasherezade/Pe-Bear,

I am sure your name will remain in history like other developers such as
ollydbg and lordpe developers because the tool you have developed is very
useful and really needed.
What I am to propose to you is to make pe-beer simpler for users, I
remember from CFFExplorer era that can be found at
https://ntcore.com/?page_id=388
Importing an existing library function to a PE was a matter of sum clicks,
no manual entry needed. You can download CFFExplorer and test yourself.

Regards,
Hossein Mirheydari

**Comment by hasherezade** [comment]
@hmirheydari - thank you for your remarks. I get it that for most users adding imports manually may be too inconvenient, and I am agree with you that this should be simplified. I was planning to do it somewhere along the way, but other priorities took over. I will add automated import adding as another feature, in the next version.
I already have the [automated implementation in my another program, IAT Patcher](https://github.com/hasherezade/IAT_patcher/blob/04dd6b31ffc4a35c9cc663bcb323c73f49c43285/patcher/StubMaker.cpp#L460), so it will be easy to adapt.

**Comment by hasherezade** [comment]
@hmirheydari - maybe you will like to test the new creator that I added:

![imports_add_creator](https://user-images.githubusercontent.com/3115348/216830703-eaed94a6-9fd5-47e7-aaa9-31e1d78dd3a4.png)

I am still improving it. The  final version will be ready for the upcoming release.
For now the test version is available via AppVeyor build server - details how to get it are in [the README](https://github.com/hasherezade/pe-bear#builds)

**Comment by hasherezade** [comment]
available in the latest release: 
+ https://github.com/hasherezade/pe-bear/releases/tag/v0.6.5
