### ISSUE TITLE
it can't be installed on Mac M1

### ISSUE THREAD

**Issue by Aviral2642** [hasherezade/pe-bear#20]
The Mac release doesn't work and when I open it there is a just a blank screen like this :- 

<img width="1512" alt="Screenshot 2023-02-26 at 12 50 30 AM" src="https://user-images.githubusercontent.com/26358686/221375765-13e85970-13c4-470d-9cfb-478d0e2074e7.png"> 

and when I try to build it it gives this error :- 

Trying to build PE-bear...
QMake version 3.1 Using Qt version 5.15.8 in /opt/homebrew/Cellar/qt@5/5.15.8_2/lib
[+] Qt5 found!
[+] CMake found!
cmake version 3.25.1 CMake suite maintained and supported by Kitware (kitware.com/cmake).
mkdir: build_qt5: File exists
[+] build directory created
CMake Error at CMakeLists.txt:65 (add_subdirectory):
  The source directory

    /Users/aviralsrivastava/pe-bear/capstone

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:68 (add_subdirectory):
  add_subdirectory given source "bearparser/parser" which is not an existing
  directory.

-- capstone_includes='/Users/aviralsrivastava/pe-bear/capstone/include'
-- capstone_lib='$<TARGET_FILE:capstone>'
-- sigfind_dir='/Users/aviralsrivastava/pe-bear/sig_finder'
-- sigfind_lib='$<TARGET_FILE:sig_finder>'
-- parser_dir='/Users/aviralsrivastava/pe-bear/bearparser/parser'
-- parser_lib='$<TARGET_FILE:bearparser>'
-- disasm_dir='/Users/aviralsrivastava/pe-bear/disasm'
-- disasm_lib='/Users/aviralsrivastava/pe-bear/disasm'
-- Configuring incomplete, errors occurred!
See also "/Users/aviralsrivastava/pe-bear/build_qt5/CMakeFiles/CMakeOutput.log".
See also "/Users/aviralsrivastava/pe-bear/build_qt5/CMakeFiles/CMakeError.log".
make: Makefile: No such file or directory
make: *** No rule to make target `Makefile'.  Stop.
make: *** No targets specified and no makefile found.  Stop.

I tried with build.sh and build_qt5 but it gives same error.

**Comment by hasherezade** [comment]
hi @Aviral2642 !
so regarding building, it seems you downloaded only PE-bear code, and not the submodules. Please clone it recursively as it was described in the README and it should solve the problem:
https://github.com/hasherezade/pe-bear#clone

Regarding the "empty screen" - not sure what do you mean, this is the initial screen when no sample was loaded. did you try to drag and drop a PE file on it? I unfortunately don't have access to a MacOS machine right now to check it.

**Comment by Aviral2642** [comment]
thanks mate, the problem is solved

**Comment by hasherezade** [comment]
@Aviral2642 - cool, was you able to load a file? or build from the source? or both?

**Comment by Aviral2642** [comment]
both

**Comment by hasherezade** [comment]
ok
