### ISSUE TITLE
PE-bear hangs on loading PE (Corkami: manyimportsW7)

### ISSUE THREAD

**Issue by greenozon** [hasherezade/pe-bear#23]
Version used:
![image](https://user-images.githubusercontent.com/765343/225430924-83014b73-f72e-43da-bc2b-dce9a8a39133.png)

Looks like it is super memory hungry while loading this PE
it can't stop and eats all the RAM...
eg:
![image](https://user-images.githubusercontent.com/765343/225430573-ef4e13e4-2a46-4075-ad18-10d80ca09cec.png)

PE:
[pe-hangs.zip](https://github.com/hasherezade/pe-bear/files/10984133/pe-hangs.zip)

**Comment by hasherezade** [comment]
hi @greenozon ! thank you for reporting, I will check it and fix soon

**Comment by hasherezade** [comment]
ok, I see why it gets stuck - the Import Table is really big, and contains a lot of nonsensical entries:

![imports](https://user-images.githubusercontent.com/3115348/225455014-5d142dfb-b5a2-4b73-b4dc-9ac5bb429504.png)

PE-bear tries to parse each of them, rather than just discarding them.

**Comment by greenozon** [comment]
Good catch!
time for party now 👍

**Comment by hasherezade** [comment]
@greenozon  - I fixed it, the new build is gonna be available at AppVeyor soon: https://github.com/hasherezade/pe-bear#builds
Please check it out and let me know if everything is ok.

**Comment by hasherezade** [comment]
BTW - where is this binary from? what is the license? I wonder if I can add it to my repository of testcases...

**Comment by greenozon** [comment]
Thank you for a super quick fix!, all is fine, app is not RAM greedy anymore and behaves very well :)
![image](https://user-images.githubusercontent.com/765343/225576104-e92ecda7-47f5-452b-a30c-bd144681f7d0.png)


 feel free to add as TC to your collection
