### ISSUE TITLE
NumberOfRvaAndSizes is ignored when reading data directories

### ISSUE THREAD

**Issue by IanLilleyT** [hasherezade/pe-bear#31]
Always reads 16 data directories, even when `NumberOfRvaAndSizes` is lower (`SizeOfOptionalHeader` is adjusted accordingly)

From the PE documentation:

> Note that the number of directories is not fixed. Before looking for a specific directory, check the NumberOfRvaAndSizes field in the optional header.

Here's a simple executable showing the problem: [test.exe](https://github.com/hasherezade/pe-bear/files/11643052/test.exe.txt) (I had to add `.txt` to upload it here)

This file has two data directories. The rest are being interpreted from the section header, which starts at `0xD8` (notice how Resource Directory also thinks it's located at `0xD8`).

![image](https://github.com/hasherezade/pe-bear/assets/1328450/e741337b-bdb0-4854-b8da-5e4833b8d772)

Thanks for reading - this is a really nice tool!

**Comment by hasherezade** [comment]
hi @IanLilleyT ! thanks for reporting. It will be fixed soon.

**Comment by hasherezade** [comment]
@IanLilleyT - I fixed it, please check the updated version and let me know if everything is fine: https://ci.appveyor.com/project/hasherezade/pe-bear/builds/47217430/job/busafyrhhuy9ogka/artifacts 
The fix will be included in the next release.

**Comment by IanLilleyT** [comment]
Works great, thanks!
