### ISSUE TITLE
GuardCFFunctionTable bug

### ISSUE THREAD

**Issue by MisakaRay2021** [hasherezade/pe-bear#32]
I checked the issue history and found that this bug has been fixed, but it seems that it has not been completely fixed. The length of metadata should be determined according to GuardFlags
![image](https://github.com/hasherezade/pe-bear/assets/79502898/855304c6-c20b-4b3d-8207-fe31bf7dba00)

**Comment by hasherezade** [comment]
hi @MisakaRay2021 !
please show me what version of PE-bear are you using.
and what is the testcase on which you observed this behavior?

**Comment by hasherezade** [comment]
@MisakaRay2021 - please check the latest builds: 
https://ci.appveyor.com/project/hasherezade/pe-bear/build/job/aumfbo7v3e91oea6/artifacts
and let me know if it is ok.

**Comment by MisakaRay2021** [comment]
> @MisakaRay2021 - please check the latest builds: https://ci.appveyor.com/project/hasherezade/pe-bear/build/job/aumfbo7v3e91oea6/artifacts and let me know if it is ok.

It worked!
![image](https://github.com/hasherezade/pe-bear/assets/79502898/0ff9a0e1-e229-4393-b7ad-43605a9883db)

**Comment by hasherezade** [comment]
great, thanks for your contribution in making PE-bear better :)
