### ISSUE TITLE
Feature request - allow files with a non .exe/.DLL in the file name to be opened 

### ISSUE THREAD

**Issue by spookleys** [hasherezade/pe-bear#47]
Hello,

Often times I need to open PE files with PeBear where the file name does not end in a .exe or .DLL extension, e.g. the file name may just be a file hash/.bin/.virus etc.

Currently trying to open these in PEBear generates an error that it cannot open the file. The file needs to be renamed to have a .exe or .DLL extension in order for it to be opened.

It would be great to have the ability to open PE files where the file extension in the file name need not be .exe/.dll

**Comment by hasherezade** [comment]
Hi @spookleys !
To be honest I don't know what do you mean, you can open freely a file with any extension, if only it follows PE format. It can be done by: `File`-> `Load PEs` -> and then choosing the filter "All files". You can also drag&drop the file directly (but the drag&drop doesn't work if PE-bear is run as Administrator).

**Comment by spookleys** [comment]
I have no idea now - I was consistently running in to this issue on my VM. Re-downloaded PE Bear and it has gone. Likely user error. I will see if I can reproduce in the future.

Apologies for wasting your time.

**Comment by hasherezade** [comment]
No problem! I am glad that it is clarified, and everything works.
