### ISSUE TITLE
Inverted pageable characteristic for sections

### ISSUE THREAD

**Issue by jonomango** [hasherezade/pe-bear#54]
In the section viewer, sections with the `IMAGE_SCN_MEM_NOT_PAGED` characteristic are shown as "pageable" instead of "non-pageable".

![image](https://github.com/hasherezade/pe-bear/assets/26609800/dbd331f8-ecda-48da-9ad9-3ed9b8a9a8a3)

**Comment by hasherezade** [comment]
Hi @jonomango ! Thank you for reporting. It should be fixed now. Please check out the latest builds:
https://ci.appveyor.com/project/hasherezade/pe-bear/builds/50004219/job/akaf5m24hrmn1yim/artifacts
