### ISSUE TITLE
You cannot open a Chinese file name from the Explorer menu, but you can open it by dragging the file

### ISSUE THREAD

**Issue by yangfan6888** [hasherezade/pe-bear#56]
![Uploading 20240910-100825.jpg…]()

**Comment by yangfan6888** [comment]
![Uploading 20240910-100825.jpg…]()

**Comment by hasherezade** [comment]
hi @yangfan6888 ! It should be fixed now. Please check the latest builds: 
https://ci.appveyor.com/project/hasherezade/pe-bear/build/job/xuk7hiy590hxlfal/artifacts
And let me know if it works.
