### ISSUE TITLE
Feature request: display section size

### ISSUE THREAD

**Issue by mehrdadn** [hasherezade/pe-bear#57]
It would be great if the raw size of each section (in the binary) could be displayed in front of it in the tree on the left, e.g.:
```
.text: 1,234 bytes
````
This would quickly help users narrow down the largest sections comprising the binary.

**Comment by hasherezade** [comment]
Hi @mehrdadn ! Thanks for the suggestion. But, TBH, I am not convinced that this feature is really needed. It will unnecessarily clutter the view. To quickly see what sections are the largest, you can look at the visualization on the right. You may also add the labels showing you the names of the sections:

![panel](https://github.com/user-attachments/assets/ca564e3f-c959-47a5-8d69-13b36aec5f70)

And more details, such as sections sizes, can anyways be checked in the "Sections Headers" panel - so I am not convinced that we really need to repeat all this information in the main tree.

![sections](https://github.com/user-attachments/assets/302e1e70-b956-4d82-bb40-5b2704fd7686)

**Comment by mehrdadn** [comment]
I hadn't seen that pane before, I think that's pretty adequate. Thank you!
