### ISSUE TITLE
provide pdb files with release version

### ISSUE THREAD

**Issue by maolike** [hasherezade/pe-bear#58]
I can't build successful on my local pc;
Can anyone provide me with pdb files for debugging?
I need v0.7.0 pdb files to debug.

**Comment by hasherezade** [comment]
hi @maolike ! Check the builds at the [AppVeyor server](https://ci.appveyor.com/project/hasherezade/pe-bear)
If you download the Debug version, there is a pdb file in the package. For example here: https://ci.appveyor.com/project/hasherezade/pe-bear/build/job/aw37fvd0yx4xm68l/artifacts
