### ISSUE TITLE
Ability to see/search strings from within PE-Bear

### ISSUE THREAD

**Issue by qwertzy-antonio-godinho** [hasherezade/pe-bear#9]
Would be great if PE-Bear would display a list of all the strings and allow filtering them (both ANSI and Unicode), as an example (screen taken from die):
![die_example_search_func](https://user-images.githubusercontent.com/74644600/99875817-5f87a980-2bea-11eb-82bc-1a75783c18d3.png)

**Comment by hasherezade** [comment]
Added in the release [0.6.7](https://github.com/hasherezade/pe-bear/releases/tag/v0.6.7)
